### ISSUE TITLE
Migration in Django  2.0.1

### ISSUE THREAD

**Issue by Ecozzo** [michaelbrooks/django-twitter-stream#13]
I'm using Django 2.0.1, so without South. Because of that, when I run python manage.py migrate, I got errors.
Is the solution to downgrade to Djando 1.6 and install South?

**Comment by michaelbrooks** [comment]
You don't actually need to use South with this project. It is probably better to use a newer version of Django if possible. Using the existing model code, you can probably use the `makemigrations` command to create new migrations (delete the old ones first). You may need to make some further changes to get the app to run on Django 2, but I don't think the migrations will be too much of a challenge.

**Comment by Ecozzo** [comment]
Thanks!
It works!
