### ISSUE TITLE
import fields in Models

### ISSUE THREAD

**Issue by lyanaz** [michaelbrooks/django-twitter-stream#5]
What is the 
"import fields" in the Models line 11. I'm using Django 1.8
Unable to run the app.

**Comment by michaelbrooks** [comment]
Oh, that would be the [django-fields](https://github.com/svetlyak40wt/django-fields) library. I forgot to include that in the setup.py -- you may also need to add it to your Django settings INSTALLED_APPS.

**Comment by lyanaz** [comment]
Thanks for the response. I was able to fix this. It turns out that fields was your custom model so to say, I had to import it.

**Comment by michaelbrooks** [comment]
Oh, sorry, you are right. It's been a while since I wrote that... Glad you got it working.
